export const imageData=[
    {
        id:1,
        category:'Home Animals',
        details:[
            {
                img:require('../assets/images/dog.png'),
                text:'dog'
            },
            {
                img:require('../assets/images/cat.png'),
                text:'cat'
            },
            {
                img:require('../assets/images/horse.png'),
                text:'horse'
            },
            {
                img:require('../assets/images/cow.png'),
                text:'cow'
            },
            {
                img:require('../assets/images/goldfish.png'),
                text:'goldfish'
            },
        ]
    },
    {
        id:2,
        category:'Wild Animals',
        details:[
            {
                img:require('../assets/images/lion.png'),
                text:'lion'
            },
            {
                img:require('../assets/images/elephant.png'),
                text:'elephant'
            },
            {
                img:require('../assets/images/bear.png'),
                text:'bear'
            },
            {
                img:require('../assets/images/tiger.png'),
                text:'tiger'
            },
            {
                img:require('../assets/images/monkey.png'),
                text:'monkey'
            },
            {
                img:require('../assets/images/fox.png'),
                text:'fox'
            },
            {
                img:require('../assets/images/kangaroo.png'),
                text:'kangaroo'
            },
            {
                img:require('../assets/images/wolf.png'),
                text:'wolf'
            },
            {
                img:require('../assets/images/bison.png'),
                text:'bison'
            },
        ]
    },
    {
        id:3,
        category:'Water Animals',
        details:[
            {
                img:require('../assets/images/jellyfish.png'),
                text:'jellyfish'
            },
            {
                img:require('../assets/images/dolphin.png'),
                text:'dolphin'
            },
            {
                img:require('../assets/images/seal.png'),
                text:'seal'
            },
            {
                img:require('../assets/images/turtle.png'),
                text:'turtle'
            },
            {
                img:require('../assets/images/shark.png'),
                text:'shark'
            },
            {
                img:require('../assets/images/seahorse.png'),
                text:'seahorse'
            },
            {
                img:require('../assets/images/eel.png'),
                text:'eel'
            },
            {
                img:require('../assets/images/octopus.png'),
                text:'octopus'
            },
            {
                img:require('../assets/images/crab.png'),
                text:'crab'
            },
        ]
    }
]